/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softproj;

/**
 *
 * @author Yahia Arafat
 */
public class Meeting extends javax.swing.JPanel {

    /**
     * Creates new form Meeting
     */
    public Meeting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SignOut = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        SearchText = new javax.swing.JTextField();
        Meeting = new javax.swing.JButton();
        Holiday = new javax.swing.JButton();
        AcceptButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MeetingTable = new javax.swing.JTable();
        MOJY = new javax.swing.JLabel();
        Tasks1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignOut.setBackground(new java.awt.Color(153, 0, 0));
        SignOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SignOut.setText("Sign Out");
        SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutActionPerformed(evt);
            }
        });
        jPanel1.add(SignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 25, 111, 48));

        SearchButton.setBackground(new java.awt.Color(102, 102, 102));
        SearchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchButton.setText("Search...");
        jPanel1.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 25, 114, 48));

        SearchText.setBackground(new java.awt.Color(204, 204, 204));
        SearchText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextActionPerformed(evt);
            }
        });
        jPanel1.add(SearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 25, 273, 48));

        Meeting.setBackground(new java.awt.Color(102, 102, 102));
        Meeting.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Meeting.setText("Meeting");
        Meeting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeetingActionPerformed(evt);
            }
        });
        jPanel1.add(Meeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 139, 57));

        Holiday.setBackground(new java.awt.Color(102, 102, 102));
        Holiday.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Holiday.setText("Holiday");
        jPanel1.add(Holiday, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 60));

        AcceptButton.setBackground(new java.awt.Color(204, 0, 51));
        AcceptButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AcceptButton.setText("Accept");
        AcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AcceptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 139, 57));

        MeetingTable.setBackground(new java.awt.Color(255, 51, 51));
        MeetingTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MeetingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number of Meeting", "Date", "accept/reject"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(MeetingTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 550, 170));

        MOJY.setFont(new java.awt.Font("Cooper Black", 1, 55)); // NOI18N
        MOJY.setText("MOJY");
        jPanel1.add(MOJY, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 60));

        Tasks1.setBackground(new java.awt.Color(102, 102, 102));
        Tasks1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Tasks1.setText("Tasks");
        Tasks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tasks1ActionPerformed(evt);
            }
        });
        jPanel1.add(Tasks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 139, 57));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yahia Arafat\\Documents\\NetBeansProjects\\SoftProj\\3333.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 1000, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 924, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignOutActionPerformed

    private void SearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextActionPerformed

    private void MeetingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeetingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MeetingActionPerformed

    private void AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptButtonActionPerformed

    private void Tasks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tasks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tasks1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JButton Holiday;
    private javax.swing.JLabel MOJY;
    private javax.swing.JButton Meeting;
    private javax.swing.JTable MeetingTable;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchText;
    private javax.swing.JButton SignOut;
    private javax.swing.JButton Tasks1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
